package monnef.dawn.client.model;

/*
 * Copyright (c) 2013 monnef.
 */

// Date: 12.4.2013 22:07:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSymbol2 extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;

    public ModelSymbol2() {
        textureWidth = 64;
        textureHeight = 64;

        Shape1 = new ModelRenderer(this, 19, 10);
        Shape1.addBox(0F, 0F, 0F, 10, 1, 1);
        Shape1.setRotationPoint(-2F, 1F, 0F);
        Shape1.setTextureSize(64, 64);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 21, 7);
        Shape2.addBox(0F, 0F, 0F, 8, 1, 1);
        Shape2.setRotationPoint(-1F, 0F, 0F);
        Shape2.setTextureSize(64, 64);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 17, 13);
        Shape3.addBox(0F, 0F, 0F, 12, 12, 1);
        Shape3.setRotationPoint(-3F, 2F, 0F);
        Shape3.setTextureSize(64, 64);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 19, 27);
        Shape4.addBox(0F, 0F, 0F, 10, 2, 1);
        Shape4.setRotationPoint(-2F, 14F, 0F);
        Shape4.setTextureSize(64, 64);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 21, 31);
        Shape5.addBox(0F, 0F, 0F, 8, 2, 1);
        Shape5.setRotationPoint(-1F, 16F, 0F);
        Shape5.setTextureSize(64, 64);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 23, 35);
        Shape6.addBox(0F, 0F, 0F, 6, 2, 1);
        Shape6.setRotationPoint(0F, 18F, 0F);
        Shape6.setTextureSize(64, 64);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 25, 39);
        Shape7.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape7.setRotationPoint(1F, 20F, 0F);
        Shape7.setTextureSize(64, 64);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
    }
}
