package monnef.dawn.client.model;

/*
 * Copyright (c) 2013 monnef.
 */

// Date: 12.4.2013 22:08:58
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSymbol3 extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;

    public ModelSymbol3() {
        textureWidth = 64;
        textureHeight = 32;

        Shape1 = new ModelRenderer(this, 45, 21);
        Shape1.addBox(0F, 0F, 0F, 5, 1, 4);
        Shape1.setRotationPoint(0F, 18F, -2F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 47, 0);
        Shape2.addBox(0F, 0F, 0F, 5, 2, 3);
        Shape2.setRotationPoint(-0.5F, 16F, -1.5F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 27, 21);
        Shape3.addBox(0F, 0F, 0F, 3, 1, 5);
        Shape3.setRotationPoint(-4.3F, 18F, -2.5F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 28, 13);
        Shape4.addBox(0F, 0F, 0F, 6, 2, 4);
        Shape4.setRotationPoint(-4F, 16F, -2F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 28, 0);
        Shape5.addBox(0F, 0F, 0F, 5, 7, 4);
        Shape5.setRotationPoint(-4F, 9F, -2F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 8, 21);
        Shape6.addBox(0F, 0F, 0F, 5, 1, 1);
        Shape6.setRotationPoint(-6F, 11F, -3F);
        Shape6.setTextureSize(64, 32);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 10, 24);
        Shape7.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape7.setRotationPoint(-5F, 12F, -3F);
        Shape7.setTextureSize(64, 32);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 5, 18);
        Shape8.addBox(0F, 0F, 0F, 7, 1, 1);
        Shape8.setRotationPoint(-8F, 10F, -3F);
        Shape8.setTextureSize(64, 32);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
        Shape9 = new ModelRenderer(this, 21, 21);
        Shape9.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape9.setRotationPoint(-1F, 10.5F, -3F);
        Shape9.setTextureSize(64, 32);
        Shape9.mirror = true;
        setRotation(Shape9, 0F, 0F, 0F);
        Shape10 = new ModelRenderer(this, 6, 0);
        Shape10.addBox(0F, 0F, 0F, 7, 1, 1);
        Shape10.setRotationPoint(-7F, 10F, 2F);
        Shape10.setTextureSize(64, 32);
        Shape10.mirror = true;
        setRotation(Shape10, 0F, 0F, 0F);
        Shape11 = new ModelRenderer(this, 10, 3);
        Shape11.addBox(0F, 0F, 0F, 5, 1, 1);
        Shape11.setRotationPoint(-5F, 11F, 2F);
        Shape11.setTextureSize(64, 32);
        Shape11.mirror = true;
        setRotation(Shape11, 0F, 0F, 0F);
        Shape12 = new ModelRenderer(this, 12, 6);
        Shape12.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape12.setRotationPoint(-4F, 12F, 2F);
        Shape12.setTextureSize(64, 32);
        Shape12.mirror = true;
        setRotation(Shape12, 0F, 0F, 0F);
        Shape13 = new ModelRenderer(this, 23, 0);
        Shape13.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape13.setRotationPoint(0F, 10.5F, 2F);
        Shape13.setTextureSize(64, 32);
        Shape13.mirror = true;
        setRotation(Shape13, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
        Shape12.render(f5);
        Shape13.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
    }
}
