// Date: 9.4.2013 16:52:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package monnef.dawn.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHat extends ModelBase {
    //fields
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;

    public ModelHat() {
        textureWidth = 128;
        textureHeight = 64;

        Shape2 = new ModelRenderer(this, 32, 9);
        Shape2.addBox(0F, 0F, 0F, 9, 1, 1);
        Shape2.setRotationPoint(0F, 23F, -6F);
        Shape2.setTextureSize(128, 64);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, -0.2974289F, 0F);
        Shape3 = new ModelRenderer(this, 32, 6);
        Shape3.addBox(0F, 0F, 0F, 7, 1, 1);
        Shape3.setRotationPoint(0F, 22F, -6F);
        Shape3.setTextureSize(128, 64);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, -0.2974289F, 0F);
        Shape4 = new ModelRenderer(this, 32, 3);
        Shape4.addBox(0F, 0F, 0F, 6, 1, 1);
        Shape4.setRotationPoint(0F, 21F, -6F);
        Shape4.setTextureSize(128, 64);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, -0.2974289F, 0F);
        Shape5 = new ModelRenderer(this, 32, 0);
        Shape5.addBox(0F, 0F, 0F, 5, 1, 1);
        Shape5.setRotationPoint(0F, 20F, -6F);
        Shape5.setTextureSize(128, 64);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, -0.2974289F, 0F);
        Shape6 = new ModelRenderer(this, 0, 15);
        Shape6.addBox(0F, 0F, 0F, 5, 1, 1);
        Shape6.setRotationPoint(0F, 20F, 5F);
        Shape6.setTextureSize(128, 64);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0.2974216F, 0F);
        Shape7 = new ModelRenderer(this, 0, 18);
        Shape7.addBox(0F, 0F, 0F, 6, 1, 1);
        Shape7.setRotationPoint(0F, 21F, 5F);
        Shape7.setTextureSize(128, 64);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0.2974216F, 0F);
        Shape8 = new ModelRenderer(this, 0, 21);
        Shape8.addBox(0F, 0F, 0F, 7, 1, 1);
        Shape8.setRotationPoint(0F, 22F, 5F);
        Shape8.setTextureSize(128, 64);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0.2974216F, 0F);
        Shape9 = new ModelRenderer(this, 0, 24);
        Shape9.addBox(0F, 0F, 0F, 9, 1, 1);
        Shape9.setRotationPoint(0F, 23F, 5F);
        Shape9.setTextureSize(128, 64);
        Shape9.mirror = true;
        setRotation(Shape9, 0F, 0.2974216F, 0F);
        Shape10 = new ModelRenderer(this, 66, 3);
        Shape10.addBox(0F, 0F, 0F, 6, 1, 1);
        Shape10.setRotationPoint(-5.75F, 21F, -4.25F);
        Shape10.setTextureSize(128, 64);
        Shape10.mirror = true;
        setRotation(Shape10, 0F, 0.2974216F, 0F);
        Shape11 = new ModelRenderer(this, 66, 9);
        Shape11.addBox(0F, 0F, 0F, 9, 1, 1);
        Shape11.setRotationPoint(-8.6F, 23F, -3.35F);
        Shape11.setTextureSize(128, 64);
        Shape11.mirror = true;
        setRotation(Shape11, 0F, 0.2974216F, 0F);
        Shape12 = new ModelRenderer(this, 66, 6);
        Shape12.addBox(0F, 0F, 0F, 7, 1, 1);
        Shape12.setRotationPoint(-6.7F, 22F, -3.95F);
        Shape12.setTextureSize(128, 64);
        Shape12.mirror = true;
        setRotation(Shape12, 0F, 0.2974216F, 0F);
        Shape13 = new ModelRenderer(this, 66, 0);
        Shape13.addBox(0F, 0F, 0F, 5, 1, 1);
        Shape13.setRotationPoint(-4.8F, 20F, -4.55F);
        Shape13.setTextureSize(128, 64);
        Shape13.mirror = true;
        setRotation(Shape13, 0F, 0.2974216F, 0F);
        Shape14 = new ModelRenderer(this, 26, 15);
        Shape14.addBox(0F, 0F, 0F, 5, 1, 1);
        Shape14.setRotationPoint(-4.1F, 20F, 3.45F);
        Shape14.setTextureSize(128, 64);
        Shape14.mirror = true;
        setRotation(Shape14, 0F, -0.2974216F, 0F);
        Shape15 = new ModelRenderer(this, 26, 19);
        Shape15.addBox(0F, 0F, 0F, 6, 1, 1);
        Shape15.setRotationPoint(-5.1F, 21F, 3.15F);
        Shape15.setTextureSize(128, 64);
        Shape15.mirror = true;
        setRotation(Shape15, 0F, -0.2974216F, 0F);
        Shape16 = new ModelRenderer(this, 26, 22);
        Shape16.addBox(0F, 0F, 0F, 7, 1, 1);
        Shape16.setRotationPoint(-6.1F, 22F, 2.85F);
        Shape16.setTextureSize(128, 64);
        Shape16.mirror = true;
        setRotation(Shape16, 0F, -0.2974216F, 0F);
        Shape17 = new ModelRenderer(this, 26, 26);
        Shape17.addBox(0F, 0F, 0F, 9, 1, 1);
        Shape17.setRotationPoint(-7.9F, 23F, 2.3F);
        Shape17.setTextureSize(128, 64);
        Shape17.mirror = true;
        setRotation(Shape17, 0F, -0.2974216F, 0F);
        Shape18 = new ModelRenderer(this, 49, 29);
        Shape18.addBox(0F, 0F, 0F, 6, 1, 6);
        Shape18.setRotationPoint(2F, 21.5F, -3F);
        Shape18.setTextureSize(128, 64);
        Shape18.mirror = true;
        setRotation(Shape18, 0F, 0F, 0.238602F);
        Shape19 = new ModelRenderer(this, 16, 0);
        Shape19.addBox(0F, 0F, 0F, 1, 1, 6);
        Shape19.setRotationPoint(7.8F, 23F, -3F);
        Shape19.setTextureSize(128, 64);
        Shape19.mirror = true;
        setRotation(Shape19, 0F, 0F, 0F);
        Shape20 = new ModelRenderer(this, 48, 39);
        Shape20.addBox(0F, 0F, 0F, 6, 1, 6);
        Shape20.setRotationPoint(-7.8F, 23F, -3F);
        Shape20.setTextureSize(128, 64);
        Shape20.mirror = true;
        setRotation(Shape20, 0F, 0F, -0.238604F);
        Shape21 = new ModelRenderer(this, 0, 0);
        Shape21.addBox(0F, 0F, 0F, 1, 1, 6);
        Shape21.setRotationPoint(-8.3F, 23F, -3F);
        Shape21.setTextureSize(128, 64);
        Shape21.mirror = true;
        setRotation(Shape21, 0F, 0F, 0F);
        Shape22 = new ModelRenderer(this, 49, 16);
        Shape22.addBox(0F, 0F, 0F, 5, 1, 8);
        Shape22.setRotationPoint(-2F, 21.45F, -4F);
        Shape22.setTextureSize(128, 64);
        Shape22.mirror = true;
        setRotation(Shape22, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        render(f5);
    }

    public void render(float f5) {
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
        Shape9.render(f5);
        Shape10.render(f5);
        Shape11.render(f5);
        Shape12.render(f5);
        Shape13.render(f5);
        Shape14.render(f5);
        Shape15.render(f5);
        Shape16.render(f5);
        Shape17.render(f5);
        Shape18.render(f5);
        Shape19.render(f5);
        Shape20.render(f5);
        Shape21.render(f5);
        Shape22.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    }
}
