package monnef.dawn.client.model;

/*
 * Copyright (c) 2013 monnef.
 */

// Date: 12.4.2013 22:06:10
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSymbol1 extends ModelBase {
    //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;

    public ModelSymbol1() {
        textureWidth = 128;
        textureHeight = 64;

        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(0F, 0F, 0F, 2, 15, 1);
        Shape1.setRotationPoint(3.5F, 7F, -1F);
        Shape1.setTextureSize(128, 64);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0.622391F);
        Shape2 = new ModelRenderer(this, 0, 18);
        Shape2.addBox(0F, 0F, 0F, 4, 1, 3);
        Shape2.setRotationPoint(-5.5F, 18F, -2F);
        Shape2.setTextureSize(128, 64);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0.622391F);
        Shape3 = new ModelRenderer(this, 0, 25);
        Shape3.addBox(0F, 0F, 0F, 1, 4, 1);
        Shape3.setRotationPoint(-4.5F, 19F, -1F);
        Shape3.setTextureSize(128, 64);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0.622391F);
        Shape4 = new ModelRenderer(this, 33, 0);
        Shape4.addBox(0F, 0F, 0F, 2, 15, 1);
        Shape4.setRotationPoint(-5.5F, 8F, 0F);
        Shape4.setTextureSize(128, 64);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, -0.6223844F);
        Shape5 = new ModelRenderer(this, 29, 17);
        Shape5.addBox(0F, 0F, 0F, 4, 1, 3);
        Shape5.setRotationPoint(2F, 20F, -1F);
        Shape5.setTextureSize(128, 64);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, -0.6223844F);
        Shape6 = new ModelRenderer(this, 34, 24);
        Shape6.addBox(0F, 0F, 0F, 1, 4, 1);
        Shape6.setRotationPoint(3.5F, 19.5F, 0F);
        Shape6.setTextureSize(128, 64);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, -0.6223844F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
    }
}
